import type { PageSiteBundle, ProfileStudioConfig } from "@gps/core";
import { builtinThemePresets, localize } from "@gps/core";

export function generatePagesSite(config: ProfileStudioConfig): PageSiteBundle {
  const theme = builtinThemePresets.find((item) => item.key === config.themeKey) ?? builtinThemePresets[0];
  const data = JSON.stringify(
    {
      profile: config.profile,
      education: config.education,
      skills: config.skills,
      projects: config.manualProjects,
      github: config.github
    },
    null,
    2
  );

  return {
    sections: config.enabledPageSections,
    warnings: [],
    files: {
      "index.html": renderHtml(config),
      "style.css": renderCss(theme),
      "script.js": renderScript(),
      "data/github.json": data,
      "README.md": `# ${config.targetUsername}.github.io\n\nGenerated by GitHub Profile Studio.`,
      "404.html": render404(config),
      "robots.txt": "User-agent: *\nAllow: /\nSitemap: ./sitemap.xml\n",
      "sitemap.xml": renderSitemap(config),
      ".github/workflows/update-pages.yml": renderPagesWorkflow()
    }
  };
}

function renderHtml(config: ProfileStudioConfig): string {
  const name = config.profile.displayName || config.targetUsername;
  const projectCards = config.manualProjects
    .filter((project) => project.showInPages)
    .map((project) => `<article class="card"><h3>${escapeHtml(project.name)}</h3><p>${escapeHtml(project.summary)}</p><p>${project.techStack.map(escapeHtml).join(" / ")}</p></article>`)
    .join("");
  const skillBadges = config.skills
    .filter((skill) => skill.showInPages)
    .map((skill) => `<span class="badge">${escapeHtml(skill.name)}</span>`)
    .join("");

  return `<!doctype html>
<html lang="${config.locale === "zh-CN" ? "zh-CN" : "en"}">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="description" content="${escapeHtml(config.profile.bio ?? "Developer profile generated by GitHub Profile Studio")}" />
  <meta property="og:title" content="${escapeHtml(name)}" />
  <meta property="og:description" content="${escapeHtml(config.profile.bio ?? "Developer profile")}" />
  <title>${escapeHtml(name)}</title>
  <link rel="icon" href="data:image/svg+xml,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 64 64'><text y='48' font-size='48'>✨</text></svg>" />
  <link rel="stylesheet" href="./style.css" />
</head>
<body>
  <nav class="nav"><a href="#about">${localize({ en: "About", zh: "关于" }, config.locale)}</a><a href="#projects">${localize({ en: "Projects", zh: "项目" }, config.locale)}</a><button id="theme-toggle">Theme</button></nav>
  <main>
    <section class="hero">
      <img class="avatar" src="${config.profile.avatarUrl ?? `https://github.com/${config.targetUsername}.png`}" alt="${escapeHtml(name)}" />
      <div>
        <h1>${escapeHtml(name)}</h1>
        <p>${escapeHtml(config.profile.bio ?? "Learning, building, and sharing progress on GitHub.")}</p>
        <div class="actions"><a href="https://github.com/${config.targetUsername}">GitHub</a><a href="#contact">${localize({ en: "Contact", zh: "联系" }, config.locale)}</a></div>
      </div>
    </section>
    <section id="about"><h2>${localize({ en: "About", zh: "关于我" }, config.locale)}</h2><p>${escapeHtml(config.profile.status ?? "Building projects and learning in public.")}</p></section>
    <section id="skills"><h2>${localize({ en: "Skills", zh: "技能" }, config.locale)}</h2><div class="badges">${skillBadges}</div></section>
    <section id="projects"><h2>${localize({ en: "Projects", zh: "项目" }, config.locale)}</h2><div class="grid">${projectCards}</div></section>
    <section id="github"><h2>GitHub</h2><div class="stats"><span>${config.github?.contributions.totalContributions ?? 0} contributions</span><span>${config.github?.totalStars ?? 0} stars</span><span>${config.github?.totalForks ?? 0} forks</span></div></section>
    <section id="contact"><h2>${localize({ en: "Contact", zh: "联系" }, config.locale)}</h2><p>${config.socialLinks.map((link) => `<a href="${link.url}">${escapeHtml(link.label)}</a>`).join(" ")}</p></section>
  </main>
  <script src="./script.js"></script>
</body>
</html>`;
}

function renderCss(theme: (typeof builtinThemePresets)[number]): string {
  return `:root{color-scheme:light;--primary:${theme.tokens.primary};--accent:${theme.tokens.accent};--bg:${theme.tokens.background};--fg:${theme.tokens.foreground};--border:${theme.tokens.border}}*{box-sizing:border-box}body{margin:0;font-family:${theme.tokens.fontFamily};background:var(--bg);color:var(--fg);line-height:1.6}.nav{position:sticky;top:0;display:flex;gap:16px;justify-content:center;padding:16px;border-bottom:1px solid var(--border);background:color-mix(in srgb,var(--bg) 92%,transparent)}.nav a,.nav button,.actions a{border:1px solid var(--border);border-radius:8px;padding:8px 12px;background:transparent;color:inherit;text-decoration:none}main{max-width:1120px;margin:0 auto;padding:24px}.hero{min-height:68vh;display:grid;grid-template-columns:160px 1fr;align-items:center;gap:32px}.hero h1{font-size:clamp(40px,8vw,88px);line-height:1;margin:0}.hero p{font-size:20px;max-width:680px}.avatar{width:160px;height:160px;border-radius:24px;border:1px solid var(--border)}section{padding:48px 0;border-bottom:1px solid var(--border)}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(240px,1fr));gap:16px}.card{border:1px solid var(--border);border-radius:8px;padding:18px}.badges,.stats,.actions{display:flex;flex-wrap:wrap;gap:10px}.badge,.stats span{border:1px solid var(--border);border-radius:999px;padding:6px 10px}@media(max-width:720px){.hero{grid-template-columns:1fr;min-height:auto}.avatar{width:112px;height:112px}}.dark{--bg:#0f172a;--fg:#e5e7eb;--border:#334155}`;
}

function renderScript(): string {
  return `document.getElementById("theme-toggle")?.addEventListener("click",()=>document.documentElement.classList.toggle("dark"));`;
}

function render404(config: ProfileStudioConfig): string {
  return `<!doctype html><html><head><title>Not found</title><link rel="stylesheet" href="./style.css"></head><body><main><h1>404</h1><p>${config.targetUsername}'s page was not found.</p><a href="./">Back home</a></main></body></html>`;
}

function renderSitemap(config: ProfileStudioConfig): string {
  return `<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"><url><loc>https://${config.targetUsername}.github.io/</loc></url></urlset>`;
}

function renderPagesWorkflow(): string {
  return `name: Update GitHub Pages data
on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Keep generated site fresh
        run: echo "GitHub Profile Studio update hook"
`;
}

function escapeHtml(value: string): string {
  return value
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;");
}

