import type { PageSiteBundle, ProfileStudioConfig } from "@gps/core";
import { builtinThemePresets, localeNumber } from "@gps/core";
import { checkPagesCompatibility } from "./pages-compatibility";

export function generatePagesSite(config: ProfileStudioConfig): PageSiteBundle {
  const theme = builtinThemePresets.find((item) => item.key === config.themeKey) ?? builtinThemePresets[0];
  const data = JSON.stringify(
    {
      profile: config.profile,
      education: config.education,
      skills: config.skills,
      projects: config.manualProjects,
      learningPlan: config.learningPlan,
      socialLinks: config.socialLinks,
      github: config.github,
      generatedAt: new Date().toISOString()
    },
    null,
    2
  );

  const bundle: PageSiteBundle = {
    sections: config.enabledPageSections,
    warnings: [],
    files: {
      "index.html": renderHtml(config),
      "style.css": renderCss(theme),
      "script.js": renderScript(),
      "data/github.json": data,
      "README.md": renderPagesReadme(config),
      "404.html": render404(config),
      "robots.txt": "User-agent: *\nAllow: /\nSitemap: ./sitemap.xml\n",
      "sitemap.xml": renderSitemap(config),
      ".github/workflows/update-pages.yml": renderPagesWorkflow()
    }
  };

  bundle.warnings = checkPagesCompatibility(bundle).map((issue) => issue.message);
  return bundle;
}

function renderHtml(config: ProfileStudioConfig): string {
  const name = config.profile.displayName || config.targetUsername;
  const avatar = config.profile.avatarUrl ?? `https://github.com/${config.targetUsername}.png`;
  const nav = [
    ["about", "About"],
    ["education", "Education"],
    ["skills", "Skills"],
    ["projects", "Projects"],
    ["github", "GitHub"],
    ["achievements", "Achievements"],
    ["contact", "Contact"]
  ];

  return `<!doctype html>
<html lang="${config.locale === "zh-CN" ? "zh-CN" : "en"}" data-theme="light" data-locale="${config.locale}">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="description" content="${escapeHtml(config.profile.bio ?? "Developer profile generated by GitHub Profile Studio")}" />
  <meta property="og:title" content="${escapeHtml(name)}" />
  <meta property="og:description" content="${escapeHtml(config.profile.bio ?? "Developer profile")}" />
  <meta property="og:image" content="${escapeHtml(avatar)}" />
  <title>${escapeHtml(name)}</title>
  <link rel="icon" href="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 64 64'%3E%3Crect width='64' height='64' rx='12' fill='%230969da'/%3E%3Ctext x='10' y='40' font-size='18' fill='white' font-family='Arial'%3EGPS%3C/text%3E%3C/svg%3E" />
  <link rel="stylesheet" href="./style.css" />
</head>
<body>
  <nav class="nav">
    <a class="brand" href="#hero">${escapeHtml(name)}</a>
    <div class="nav-links">${nav.map(([id, label]) => `<a href="#${id}">${label}</a>`).join("")}</div>
    <div class="nav-actions"><button id="language-toggle" type="button">EN / 中文</button><button id="theme-toggle" type="button">Theme</button></div>
  </nav>
  <main>
    ${renderHero(config, avatar, name)}
    ${renderAbout(config)}
    ${renderEducation(config)}
    ${renderSkills(config)}
    ${renderLearningDirections(config)}
    ${renderLearningPlan(config)}
    ${renderProjects(config)}
    ${renderTimeline(config)}
    ${renderGrowthRoadmap(config)}
    ${renderGitHub(config)}
    ${renderFutureGoals(config)}
    ${renderAchievements(config)}
    ${renderResume(config)}
    ${renderBlog(config)}
    ${renderContact(config)}
  </main>
  <footer class="footer">Generated by GitHub Profile Studio · <a href="https://github.com/${config.targetUsername}">@${config.targetUsername}</a></footer>
  <button id="back-to-top" type="button" aria-label="Back to top">↑</button>
  <script src="./script.js"></script>
</body>
</html>`;
}

function renderHero(config: ProfileStudioConfig, avatar: string, name: string): string {
  return `<section id="hero" class="hero">
    <img class="avatar" src="${escapeHtml(avatar)}" alt="${escapeHtml(name)}" />
    <div>
      <p class="eyebrow">${escapeHtml(config.profile.currentRole ?? "Developer")}</p>
      <h1>${escapeHtml(name)}</h1>
      <p class="lead">${escapeHtml(config.profile.bio ?? "Learning, building, and sharing progress on GitHub.")}</p>
      <div class="actions"><a href="https://github.com/${config.targetUsername}">GitHub</a><a href="#projects">Projects</a><a href="#contact">Contact</a></div>
    </div>
  </section>`;
}

function renderAbout(config: ProfileStudioConfig): string {
  return `<section id="about"><h2>About</h2><p>${escapeHtml(config.profile.status ?? "Building projects and learning in public.")}</p></section>`;
}

function renderEducation(config: ProfileStudioConfig): string {
  const items = config.education
    .filter((item) => item.showInPages)
    .map((item) => `<article class="card"><h3>${escapeHtml(item.school ?? "Education")}</h3><p>${escapeHtml([item.degree, item.major, item.department].filter(Boolean).join(" · ") || "Learning path")}</p><p>${escapeHtml(item.courses.join(" · ") || "Coursework and self-study")}</p></article>`)
    .join("");
  return `<section id="education"><h2>Education</h2><div class="grid">${items || `<article class="card"><h3>Learning</h3><p>Education details are hidden by privacy settings.</p></article>`}</div></section>`;
}

function renderSkills(config: ProfileStudioConfig): string {
  const badges = config.skills
    .filter((skill) => skill.showInPages)
    .map((skill) => `<span class="badge" title="${escapeHtml(skill.status)}">${escapeHtml(skill.name)} · ${skill.proficiency}%</span>`)
    .join("");
  return `<section id="skills"><h2>Skills</h2><div class="badges">${badges || `<span class="badge">Building fundamentals</span>`}</div></section>`;
}

function renderLearningDirections(config: ProfileStudioConfig): string {
  return `<section id="learning-directions"><h2>Learning Directions</h2><div class="badges">${config.learningPlan.currentFocus.map((item) => `<span class="badge">${escapeHtml(item)}</span>`).join("")}</div></section>`;
}

function renderLearningPlan(config: ProfileStudioConfig): string {
  return `<section id="learning-plan"><h2>Learning Plan</h2><div class="grid"><article class="card"><h3>Short term</h3>${listHtml(config.learningPlan.shortTermGoals)}</article><article class="card"><h3>Long term</h3>${listHtml(config.learningPlan.longTermGoals)}</article></div></section>`;
}

function renderProjects(config: ProfileStudioConfig): string {
  const manual = config.manualProjects
    .filter((project) => project.showInPages)
    .map((project) => `<article class="card"><h3>${escapeHtml(project.name)}</h3><p>${escapeHtml(project.summary)}</p><p>${project.techStack.map(escapeHtml).join(" / ")}</p></article>`);
  const repos = (config.github?.repositories ?? [])
    .filter((repo) => !repo.isPrivate && !repo.isArchived)
    .slice(0, 6)
    .map((repo) => `<article class="card"><h3>${escapeHtml(repo.name)}</h3><p>${escapeHtml(repo.description ?? "GitHub repository")}</p><p>${localeNumber(repo.stars, config.locale)} stars · ${localeNumber(repo.forks, config.locale)} forks</p></article>`);
  return `<section id="projects"><h2>Projects</h2><div class="grid">${[...manual, ...repos].join("") || `<article class="card"><h3>Project plan</h3><p>Projects are being prepared.</p></article>`}</div></section>`;
}

function renderTimeline(config: ProfileStudioConfig): string {
  const milestones = [
    config.profile.createdAt ? `Joined GitHub in ${new Date(config.profile.createdAt).getUTCFullYear()}` : "Started building a GitHub presence",
    config.education[0]?.startYear ? `Started ${config.education[0].major ?? "study"} in ${config.education[0].startYear}` : "Defined learning path",
    config.manualProjects[0] ? `Building ${config.manualProjects[0].name}` : "Preparing first project",
    "Publishing README, Pages, cards, and achievements"
  ];
  return `<section id="timeline"><h2>Timeline</h2><ol class="timeline">${milestones.map((item) => `<li>${escapeHtml(item)}</li>`).join("")}</ol></section>`;
}

function renderGrowthRoadmap(config: ProfileStudioConfig): string {
  return `<section id="growth-roadmap"><h2>Growth Roadmap</h2><div class="grid"><article class="card"><h3>Open source</h3><p>${escapeHtml(config.learningPlan.openSourcePlan ?? "Start with documentation fixes and small issues.")}</p></article><article class="card"><h3>Career</h3><p>${escapeHtml(config.learningPlan.jobPlan ?? "Turn projects into clear case studies.")}</p></article></div></section>`;
}

function renderGitHub(config: ProfileStudioConfig): string {
  const data = config.github;
  return `<section id="github"><h2>GitHub Data</h2><div class="stats"><span>${localeNumber(data?.contributions.totalContributions ?? 0, config.locale)} contributions</span><span>${localeNumber(data?.totalStars ?? 0, config.locale)} stars</span><span>${localeNumber(data?.totalForks ?? 0, config.locale)} forks</span><span>${localeNumber(data?.pullRequests.total ?? 0, config.locale)} PRs</span><span>${localeNumber(data?.issues.total ?? 0, config.locale)} issues</span></div></section>`;
}

function renderFutureGoals(config: ProfileStudioConfig): string {
  return `<section id="future-goals"><h2>Future Goals</h2>${listHtml(config.learningPlan.longTermGoals)}</section>`;
}

function renderAchievements(config: ProfileStudioConfig): string {
  return `<section id="achievements"><h2>Achievement Wall</h2><img class="wide-card" src="https://github-profile-studio.vercel.app/api/cards/achievements?user=${encodeURIComponent(config.targetUsername)}&theme=${encodeURIComponent(config.themeKey)}&locale=${encodeURIComponent(config.locale)}" alt="Achievement wall" /></section>`;
}

function renderResume(config: ProfileStudioConfig): string {
  return `<section id="resume"><h2>Resume</h2><p>Resume-ready summary: ${escapeHtml(config.profile.currentRole ?? "Developer")} · ${escapeHtml(config.skills.slice(0, 5).map((skill) => skill.name).join(", "))}</p></section>`;
}

function renderBlog(config: ProfileStudioConfig): string {
  const blog = config.profile.blog ?? config.socialLinks.find((link) => /blog|rss/i.test(link.provider))?.url;
  return `<section id="blog"><h2>Blog</h2><p>${blog ? `<a href="${escapeHtml(blog)}">Read recent posts</a>` : "Blog entry is ready for an RSS source."}</p></section>`;
}

function renderContact(config: ProfileStudioConfig): string {
  const links = config.socialLinks
    .filter((link) => link.showInPages)
    .map((link) => `<a href="${escapeHtml(link.url)}">${escapeHtml(link.label)}</a>`)
    .join(" ");
  return `<section id="contact"><h2>Contact</h2><p>${links || "Contact links are hidden by privacy settings."}</p></section>`;
}

function renderCss(theme: (typeof builtinThemePresets)[number]): string {
  return `:root{color-scheme:light;--primary:${theme.tokens.primary};--accent:${theme.tokens.accent};--bg:${theme.tokens.background};--fg:${theme.tokens.foreground};--muted:#57606a;--border:${theme.tokens.border}}[data-theme=dark]{color-scheme:dark;--bg:#0f172a;--fg:#e5e7eb;--muted:#cbd5e1;--border:#334155}*{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;font-family:${theme.tokens.fontFamily};background:var(--bg);color:var(--fg);line-height:1.6}.nav{position:sticky;top:0;z-index:10;display:flex;gap:16px;align-items:center;justify-content:space-between;padding:14px 24px;border-bottom:1px solid var(--border);background:color-mix(in srgb,var(--bg) 92%,transparent);backdrop-filter:blur(12px)}.brand{font-weight:700}.nav a,.nav button,.actions a{border:1px solid var(--border);border-radius:8px;padding:8px 12px;background:transparent;color:inherit;text-decoration:none}.nav-links,.nav-actions,.actions,.badges,.stats{display:flex;flex-wrap:wrap;gap:10px}main{max-width:1120px;margin:0 auto;padding:24px}.hero{min-height:66vh;display:grid;grid-template-columns:160px 1fr;align-items:center;gap:32px}.hero h1{font-size:clamp(40px,8vw,88px);line-height:1;margin:0}.lead{font-size:20px;max-width:720px}.eyebrow{color:var(--primary);font-weight:700;text-transform:uppercase}.avatar{width:160px;height:160px;border-radius:24px;border:1px solid var(--border)}section{padding:46px 0;border-bottom:1px solid var(--border)}h2{font-size:28px;margin:0 0 18px}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(240px,1fr));gap:16px}.card{border:1px solid var(--border);border-radius:8px;padding:18px;background:color-mix(in srgb,var(--bg) 96%,var(--primary))}.badge,.stats span{border:1px solid var(--border);border-radius:999px;padding:6px 10px}.timeline{display:grid;gap:12px;padding-left:20px}.wide-card{max-width:100%;border:1px solid var(--border);border-radius:8px}.footer{padding:32px;text-align:center;color:var(--muted)}#back-to-top{position:fixed;right:20px;bottom:20px;border:1px solid var(--border);border-radius:999px;width:44px;height:44px;background:var(--bg);color:var(--fg)}@media(max-width:760px){.nav{align-items:flex-start;flex-direction:column}.hero{grid-template-columns:1fr;min-height:auto}.avatar{width:112px;height:112px}.nav-links{display:none}}`;
}

function renderScript(): string {
  return `const root=document.documentElement;document.getElementById("theme-toggle")?.addEventListener("click",()=>{root.dataset.theme=root.dataset.theme==="dark"?"light":"dark"});document.getElementById("language-toggle")?.addEventListener("click",()=>{root.dataset.locale=root.dataset.locale==="zh-CN"?"en-US":"zh-CN";root.lang=root.dataset.locale==="zh-CN"?"zh-CN":"en"});document.getElementById("back-to-top")?.addEventListener("click",()=>scrollTo({top:0,behavior:"smooth"}));`;
}

function renderPagesReadme(config: ProfileStudioConfig): string {
  return `# ${config.targetUsername}.github.io\n\nGenerated by GitHub Profile Studio.\n\n## Deploy\n\nEnable GitHub Pages from branch \`main\` and path \`/\`.`;
}

function render404(config: ProfileStudioConfig): string {
  return `<!doctype html><html><head><title>Not found</title><link rel="stylesheet" href="./style.css"></head><body><main><h1>404</h1><p>${config.targetUsername}'s page was not found.</p><a href="./">Back home</a></main></body></html>`;
}

function renderSitemap(config: ProfileStudioConfig): string {
  return `<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"><url><loc>https://${config.targetUsername}.github.io/</loc></url></urlset>`;
}

function renderPagesWorkflow(): string {
  return `name: Update GitHub Pages data
on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Keep generated site fresh
        run: echo "GitHub Profile Studio update hook"
`;
}

function listHtml(items: string[]): string {
  return `<ul>${(items.length > 0 ? items : ["Plan is being prepared."]).map((item) => `<li>${escapeHtml(item)}</li>`).join("")}</ul>`;
}

function escapeHtml(value: string): string {
  return value
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;");
}
