import type { CardRequest, LocalizedText } from "@gps/core";
import { localeNumber } from "@gps/core";

export type CardDefinition = {
  type: string;
  name: LocalizedText;
  description: LocalizedText;
  defaultWidth: number;
  defaultHeight: number;
  acceptanceId: string;
};

export const cardCatalog: CardDefinition[] = [
  ["profile-overview", "Profile Overview Card", "Profile Overview Card 可用", "Profile, followers, repositories, and account age.", "06-001"],
  ["github-stats", "GitHub Stats Card", "GitHub Stats Card 可用", "Contribution, repository, star, and fork totals.", "06-002"],
  ["github-streak", "GitHub Streak Card", "GitHub Streak Card 可用", "Current and longest contribution streak.", "06-003"],
  ["contribution-calendar", "Contribution Calendar Card", "Contribution Calendar Card 可用", "Contribution heatmap for README embedding.", "06-004"],
  ["top-languages", "Top Languages Card", "Top Languages Card 可用", "Language distribution by bytes, repos, and weighted impact.", "06-005"],
  ["repository", "Repository Card", "Repository Card 可用", "Single repository summary.", "06-006"],
  ["star-growth", "Star Growth Card", "Star Growth Card 可用", "Star growth trends and milestones.", "06-007"],
  ["fork-growth", "Fork Growth Card", "Fork Growth Card 可用", "Fork growth trends.", "06-008"],
  ["pr-issue", "PR / Issue Card", "PR / Issue Card 可用", "Pull request and issue collaboration stats.", "06-009"],
  ["achievement", "Achievement Card", "Achievement Card 可用", "Unlocked achievement summary.", "06-010"],
  ["trophy", "Trophy Card", "Trophy Card 可用", "Trophy-style achievement display.", "06-011"],
  ["tech-stack", "Tech Stack Card", "Tech Stack Card 可用", "Detected and manual skills.", "06-012"],
  ["activity-graph", "Activity Graph Card", "Activity Graph Card 可用", "Monthly activity graph.", "06-013"],
  ["repo-ranking", "Repo Ranking Card", "Repo Ranking Card 可用", "Top repositories by stars, forks, and growth.", "06-014"],
  ["followers", "Followers Card", "Followers Card 可用", "Followers and following counts.", "06-015"],
  ["account-age", "Account Age Card", "Account Age Card 可用", "Account age and tenure.", "06-016"],
  ["open-source-impact", "Open Source Impact Card", "Open Source Impact Card 可用", "Community impact score.", "06-017"],
  ["year-in-review", "Year in Review Card", "Year in Review Card 可用", "Annual summary.", "06-018"],
  ["monthly-activity", "Monthly Activity Card", "Monthly Activity Card 可用", "Monthly contribution distribution.", "06-019"],
  ["custom-composite", "Custom Composite Card", "Custom Composite Card 可用", "User-defined composite card.", "06-020"]
].map(([type, en, zh, description, acceptanceId]) => ({
  type,
  name: { en, zh },
  description: { en: description, zh },
  defaultWidth: 640,
  defaultHeight: 220,
  acceptanceId
}));

export function renderCardSvg(request: CardRequest): string {
  const title = cardCatalog.find((card) => card.type === request.type)?.name.en ?? "GitHub Profile Card";
  const dataset = request.dataset;
  const stats = [
    ["Repositories", dataset.profile.publicRepos],
    ["Stars", dataset.totalStars],
    ["Forks", dataset.totalForks],
    ["Contributions", dataset.contributions.totalContributions]
  ];

  return `<svg xmlns="http://www.w3.org/2000/svg" width="640" height="220" viewBox="0 0 640 220" role="img" aria-label="${escapeXml(title)}">
  <rect width="640" height="220" rx="8" fill="#ffffff"/>
  <rect x="0.5" y="0.5" width="639" height="219" rx="8" fill="none" stroke="#d0d7de"/>
  <text x="28" y="42" font-family="Segoe UI, Arial, sans-serif" font-size="22" font-weight="700" fill="#0969da">${escapeXml(title)}</text>
  <text x="28" y="72" font-family="Segoe UI, Arial, sans-serif" font-size="14" fill="#57606a">@${escapeXml(request.user)} · ${escapeXml(request.locale)}</text>
  ${stats
    .map((item, index) => {
      const x = 28 + index * 150;
      return `<g transform="translate(${x} 112)"><text font-family="Segoe UI, Arial, sans-serif" font-size="28" font-weight="700" fill="#24292f">${localeNumber(item[1] as number, request.locale)}</text><text y="28" font-family="Segoe UI, Arial, sans-serif" font-size="13" fill="#57606a">${escapeXml(item[0] as string)}</text></g>`;
    })
    .join("")}
  <text x="28" y="198" font-family="Segoe UI, Arial, sans-serif" font-size="12" fill="#6e7781">Generated by GitHub Profile Studio</text>
</svg>`;
}

export function renderErrorSvg(message: string): string {
  return `<svg xmlns="http://www.w3.org/2000/svg" width="640" height="160" role="img"><rect width="640" height="160" rx="8" fill="#fff1f2"/><text x="24" y="56" font-size="20" font-family="Arial" fill="#be123c">Card generation failed</text><text x="24" y="92" font-size="14" font-family="Arial" fill="#881337">${escapeXml(message)}</text></svg>`;
}

function escapeXml(value: string): string {
  return value.replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;").replaceAll('"', "&quot;");
}

