import { z } from "zod";
import type { LocalizedText, StudioLocale } from "./language";
export declare const generationModeSchema: z.ZodEnum<["new-user", "data-enhanced", "hybrid", "manual"]>;
export type GenerationMode = z.infer<typeof generationModeSchema>;
export declare const targetTypeSchema: z.ZodEnum<["readme", "pages", "cards", "achievements"]>;
export type TargetType = z.infer<typeof targetTypeSchema>;
export declare const privacyScopeSchema: z.ZodEnum<["readme", "pages", "both"]>;
export type PrivacyScope = z.infer<typeof privacyScopeSchema>;
export declare const socialLinkSchema: z.ZodObject<{
    provider: z.ZodString;
    label: z.ZodString;
    url: z.ZodString;
    showInReadme: z.ZodDefault<z.ZodBoolean>;
    showInPages: z.ZodDefault<z.ZodBoolean>;
}, "strip", z.ZodTypeAny, {
    provider: string;
    label: string;
    url: string;
    showInReadme: boolean;
    showInPages: boolean;
}, {
    provider: string;
    label: string;
    url: string;
    showInReadme?: boolean | undefined;
    showInPages?: boolean | undefined;
}>;
export type SocialLink = z.infer<typeof socialLinkSchema>;
export declare const skillSchema: z.ZodObject<{
    name: z.ZodString;
    category: z.ZodEnum<["frontend", "backend", "database", "ai-data", "devops", "language", "testing", "cloud", "other"]>;
    proficiency: z.ZodNumber;
    status: z.ZodEnum<["learning", "daily-use", "primary", "interested"]>;
    showIcon: z.ZodDefault<z.ZodBoolean>;
    showBadge: z.ZodDefault<z.ZodBoolean>;
    showInReadme: z.ZodDefault<z.ZodBoolean>;
    showInPages: z.ZodDefault<z.ZodBoolean>;
}, "strip", z.ZodTypeAny, {
    status: "learning" | "daily-use" | "primary" | "interested";
    showInReadme: boolean;
    showInPages: boolean;
    name: string;
    category: "frontend" | "backend" | "database" | "ai-data" | "devops" | "language" | "testing" | "cloud" | "other";
    proficiency: number;
    showIcon: boolean;
    showBadge: boolean;
}, {
    status: "learning" | "daily-use" | "primary" | "interested";
    name: string;
    category: "frontend" | "backend" | "database" | "ai-data" | "devops" | "language" | "testing" | "cloud" | "other";
    proficiency: number;
    showInReadme?: boolean | undefined;
    showInPages?: boolean | undefined;
    showIcon?: boolean | undefined;
    showBadge?: boolean | undefined;
}>;
export type Skill = z.infer<typeof skillSchema>;
export declare const educationSchema: z.ZodObject<{
    school: z.ZodOptional<z.ZodString>;
    department: z.ZodOptional<z.ZodString>;
    major: z.ZodOptional<z.ZodString>;
    degree: z.ZodOptional<z.ZodString>;
    startYear: z.ZodOptional<z.ZodNumber>;
    graduationYear: z.ZodOptional<z.ZodNumber>;
    grade: z.ZodOptional<z.ZodString>;
    courses: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
    honors: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
    showInReadme: z.ZodDefault<z.ZodBoolean>;
    showInPages: z.ZodDefault<z.ZodBoolean>;
}, "strip", z.ZodTypeAny, {
    showInReadme: boolean;
    showInPages: boolean;
    courses: string[];
    honors: string[];
    school?: string | undefined;
    department?: string | undefined;
    major?: string | undefined;
    degree?: string | undefined;
    startYear?: number | undefined;
    graduationYear?: number | undefined;
    grade?: string | undefined;
}, {
    showInReadme?: boolean | undefined;
    showInPages?: boolean | undefined;
    school?: string | undefined;
    department?: string | undefined;
    major?: string | undefined;
    degree?: string | undefined;
    startYear?: number | undefined;
    graduationYear?: number | undefined;
    grade?: string | undefined;
    courses?: string[] | undefined;
    honors?: string[] | undefined;
}>;
export type Education = z.infer<typeof educationSchema>;
export declare const manualProjectSchema: z.ZodObject<{
    name: z.ZodString;
    summary: z.ZodString;
    type: z.ZodEnum<["personal", "course", "competition", "team", "open-source", "planned"]>;
    status: z.ZodEnum<["planned", "building", "completed", "maintained"]>;
    techStack: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
    highlights: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
    role: z.ZodOptional<z.ZodString>;
    repoUrl: z.ZodOptional<z.ZodString>;
    demoUrl: z.ZodOptional<z.ZodString>;
    imageUrl: z.ZodOptional<z.ZodString>;
    featured: z.ZodDefault<z.ZodBoolean>;
    showInReadme: z.ZodDefault<z.ZodBoolean>;
    showInPages: z.ZodDefault<z.ZodBoolean>;
}, "strip", z.ZodTypeAny, {
    type: "personal" | "course" | "competition" | "team" | "open-source" | "planned";
    status: "planned" | "building" | "completed" | "maintained";
    showInReadme: boolean;
    showInPages: boolean;
    name: string;
    summary: string;
    techStack: string[];
    highlights: string[];
    featured: boolean;
    role?: string | undefined;
    repoUrl?: string | undefined;
    demoUrl?: string | undefined;
    imageUrl?: string | undefined;
}, {
    type: "personal" | "course" | "competition" | "team" | "open-source" | "planned";
    status: "planned" | "building" | "completed" | "maintained";
    name: string;
    summary: string;
    showInReadme?: boolean | undefined;
    showInPages?: boolean | undefined;
    techStack?: string[] | undefined;
    highlights?: string[] | undefined;
    role?: string | undefined;
    repoUrl?: string | undefined;
    demoUrl?: string | undefined;
    imageUrl?: string | undefined;
    featured?: boolean | undefined;
}>;
export type ManualProject = z.infer<typeof manualProjectSchema>;
export declare const learningPlanSchema: z.ZodObject<{
    currentFocus: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
    books: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
    courses: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
    currentProjects: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
    shortTermGoals: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
    longTermGoals: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
    openSourcePlan: z.ZodOptional<z.ZodString>;
    jobPlan: z.ZodOptional<z.ZodString>;
    showInReadme: z.ZodDefault<z.ZodBoolean>;
    showInPages: z.ZodDefault<z.ZodBoolean>;
}, "strip", z.ZodTypeAny, {
    showInReadme: boolean;
    showInPages: boolean;
    courses: string[];
    currentFocus: string[];
    books: string[];
    currentProjects: string[];
    shortTermGoals: string[];
    longTermGoals: string[];
    openSourcePlan?: string | undefined;
    jobPlan?: string | undefined;
}, {
    showInReadme?: boolean | undefined;
    showInPages?: boolean | undefined;
    courses?: string[] | undefined;
    currentFocus?: string[] | undefined;
    books?: string[] | undefined;
    currentProjects?: string[] | undefined;
    shortTermGoals?: string[] | undefined;
    longTermGoals?: string[] | undefined;
    openSourcePlan?: string | undefined;
    jobPlan?: string | undefined;
}>;
export type LearningPlan = z.infer<typeof learningPlanSchema>;
export declare const userProfileSchema: z.ZodObject<{
    githubUsername: z.ZodString;
    githubId: z.ZodOptional<z.ZodNumber>;
    displayName: z.ZodOptional<z.ZodString>;
    nickname: z.ZodOptional<z.ZodString>;
    avatarUrl: z.ZodOptional<z.ZodString>;
    bio: z.ZodOptional<z.ZodString>;
    currentRole: z.ZodOptional<z.ZodString>;
    status: z.ZodOptional<z.ZodString>;
    location: z.ZodOptional<z.ZodString>;
    company: z.ZodOptional<z.ZodString>;
    blog: z.ZodOptional<z.ZodString>;
    email: z.ZodOptional<z.ZodString>;
    followers: z.ZodDefault<z.ZodNumber>;
    following: z.ZodDefault<z.ZodNumber>;
    publicRepos: z.ZodDefault<z.ZodNumber>;
    publicGists: z.ZodDefault<z.ZodNumber>;
    createdAt: z.ZodOptional<z.ZodString>;
    lastFetchedAt: z.ZodOptional<z.ZodString>;
}, "strip", z.ZodTypeAny, {
    githubUsername: string;
    followers: number;
    following: number;
    publicRepos: number;
    publicGists: number;
    status?: string | undefined;
    githubId?: number | undefined;
    displayName?: string | undefined;
    nickname?: string | undefined;
    avatarUrl?: string | undefined;
    bio?: string | undefined;
    currentRole?: string | undefined;
    location?: string | undefined;
    company?: string | undefined;
    blog?: string | undefined;
    email?: string | undefined;
    createdAt?: string | undefined;
    lastFetchedAt?: string | undefined;
}, {
    githubUsername: string;
    status?: string | undefined;
    githubId?: number | undefined;
    displayName?: string | undefined;
    nickname?: string | undefined;
    avatarUrl?: string | undefined;
    bio?: string | undefined;
    currentRole?: string | undefined;
    location?: string | undefined;
    company?: string | undefined;
    blog?: string | undefined;
    email?: string | undefined;
    followers?: number | undefined;
    following?: number | undefined;
    publicRepos?: number | undefined;
    publicGists?: number | undefined;
    createdAt?: string | undefined;
    lastFetchedAt?: string | undefined;
}>;
export type UserProfile = z.infer<typeof userProfileSchema>;
export type Repository = {
    githubRepoId: number;
    owner: string;
    name: string;
    fullName: string;
    description?: string;
    homepage?: string;
    language?: string;
    topics: string[];
    license?: string;
    stars: number;
    forks: number;
    watchers: number;
    subscribers: number;
    openIssues: number;
    size: number;
    defaultBranch: string;
    isFork: boolean;
    isArchived: boolean;
    isPrivate: boolean;
    hasPages: boolean;
    hasWiki: boolean;
    hasDiscussions: boolean;
    createdAt?: string;
    updatedAt?: string;
    pushedAt?: string;
};
export type ContributionDay = {
    date: string;
    count: number;
    level: 0 | 1 | 2 | 3 | 4;
};
export type ContributionStats = {
    username: string;
    year: number;
    totalContributions: number;
    commitContributions: number;
    issueContributions: number;
    pullRequestContributions: number;
    reviewContributions: number;
    currentStreak: number;
    longestStreak: number;
    contributionDays: ContributionDay[];
    monthlyStats: Record<string, number>;
    weeklyStats: Record<string, number>;
    hourlyStats: Record<string, number>;
    restrictedContributions?: number;
};
export type RepositoryTrend = {
    repoFullName: string;
    date: string;
    stars: number;
    forks: number;
    issues: number;
    watchers: number;
    subscribers: number;
    contributors: number;
    releaseDownloads: number;
    snapshotSource: "github-api" | "stargazer-backfill" | "scheduled-snapshot";
};
export type PullRequestStats = {
    total: number;
    merged: number;
    closed: number;
    reviewed: number;
    recentYear: number;
    mergeRate: number;
    externalRepositories: number;
    organizations: number;
};
export type IssueStats = {
    total: number;
    closed: number;
    recentYear: number;
    closeRate: number;
    participantCount: number;
};
export type LanguageStats = {
    byRepoCount: Record<string, number>;
    byBytes: Record<string, number>;
    recentYear: Record<string, number>;
    starWeighted: Record<string, number>;
    forkWeighted: Record<string, number>;
};
export type GitHubDataset = {
    profile: UserProfile;
    repositories: Repository[];
    contributions: ContributionStats;
    repositoryTrends: RepositoryTrend[];
    pullRequests: PullRequestStats;
    issues: IssueStats;
    languages: LanguageStats;
    totalStars: number;
    totalForks: number;
    technologyTags: string[];
    fetchedAt: string;
};
export type PrivacySetting = {
    key: string;
    label: LocalizedText;
    sensitive: boolean;
    scope: PrivacyScope;
    visibleInReadme: boolean;
    visibleInPages: boolean;
    obfuscation?: string;
};
export type ProfileStudioConfig = {
    locale: StudioLocale;
    mode: GenerationMode;
    targetUsername: string;
    profile: UserProfile;
    education: Education[];
    skills: Skill[];
    learningPlan: LearningPlan;
    manualProjects: ManualProject[];
    socialLinks: SocialLink[];
    themeKey: string;
    readmeTemplateKey: string;
    pageTemplateKey: string;
    enabledReadmeModules: string[];
    enabledPageSections: string[];
    privacy: PrivacySetting[];
    github?: GitHubDataset;
};
export type GeneratedReadme = {
    markdown: string;
    modules: Array<{
        id: string;
        label: LocalizedText;
        acceptanceIds: string[];
    }>;
    warnings: string[];
};
export type PageSiteBundle = {
    files: Record<string, string>;
    sections: string[];
    warnings: string[];
};
export type CardRequest = {
    type: string;
    user: string;
    locale: StudioLocale;
    dataset: GitHubDataset;
    theme: string;
    format: "svg" | "png" | "json";
    repo?: string;
    period?: "7d" | "30d" | "90d" | "365d" | "all";
};
export type AchievementRule = {
    key: string;
    category: string;
    name: LocalizedText;
    description: LocalizedText;
    icon: string;
    level: "bronze" | "silver" | "gold" | "platinum" | "legendary";
    rarity: "common" | "uncommon" | "rare" | "epic" | "legendary";
    score: number;
    target: number;
    hidden?: boolean;
    acceptanceIds: string[];
    evaluate: (dataset: GitHubDataset) => number;
};
export type AchievementResult = {
    key: string;
    name: string;
    description: string;
    icon: string;
    category: string;
    level: AchievementRule["level"];
    rarity: AchievementRule["rarity"];
    score: number;
    unlocked: boolean;
    unlockedAt?: string;
    progress: {
        current: number;
        target: number;
        percent: number;
    };
    readmeBadgeMarkdown: string;
};
