import { z } from "zod";
import type { NewUserFormDraft } from "./new-user-form";
import { newUserFormDraftSchema } from "./new-user-form";

export const pageVisualConfigSchema = z.object({
  style: z.enum(["student-portfolio", "resume", "learning-growth", "bento", "minimal", "personal-brand"]).default("student-portfolio"),
  primaryColor: z.string().default("#0969da"),
  accentColor: z.string().default("#1f883d"),
  fontFamily: z.string().default("Inter, ui-sans-serif, system-ui"),
  background: z.enum(["solid", "subtle-grid", "paper", "code", "image"]).default("solid"),
  heroLayout: z.enum(["centered", "left-aligned", "split-profile", "bento-summary"]).default("centered"),
  cardStyle: z.enum(["flat", "bordered", "compact", "bento"]).default("bordered"),
  skillIconStyle: z.enum(["badges", "icons", "progress", "cloud"]).default("badges"),
  projectCardStyle: z.enum(["compact", "case-study", "media", "timeline"]).default("case-study"),
  seo: z.object({
    title: z.string().optional(),
    description: z.string().optional(),
    keywords: z.array(z.string()).default([])
  }),
  openGraph: z.object({
    title: z.string().optional(),
    description: z.string().optional(),
    imageAlt: z.string().optional()
  }),
  favicon: z.object({
    emoji: z.string().default("GH"),
    background: z.string().default("#ffffff"),
    foreground: z.string().default("#0969da")
  }),
  staticAssets: z.array(z.object({ path: z.string(), purpose: z.string() })).default([])
});

export type PageVisualConfig = z.infer<typeof pageVisualConfigSchema>;

export function defaultPageVisualConfig(draft: NewUserFormDraft): PageVisualConfig {
  const parsed = newUserFormDraftSchema.parse(draft);
  const titleName = parsed.basics.displayName || parsed.basics.nickname || parsed.username;
  const focus = parsed.learning.directions.slice(0, 3);

  return {
    style: parsed.contact.showResume ? "resume" : "student-portfolio",
    primaryColor: "#0969da",
    accentColor: "#1f883d",
    fontFamily: "Inter, ui-sans-serif, system-ui",
    background: "solid",
    heroLayout: parsed.manualProjects.length > 2 ? "bento-summary" : "centered",
    cardStyle: parsed.manualProjects.length > 3 ? "bento" : "bordered",
    skillIconStyle: parsed.display.showSkillProgress ? "progress" : "badges",
    projectCardStyle: parsed.manualProjects.some((project) => project.imageUrl) ? "media" : "case-study",
    seo: {
      title: `${titleName} - GitHub Portfolio`,
      description: parsed.basics.oneLineIntro || `${titleName}'s GitHub profile, projects, and learning roadmap.`,
      keywords: [parsed.username, ...focus, ...parsed.languages.map((language) => language.name)].filter(Boolean)
    },
    openGraph: {
      title: `${titleName} - GitHub Portfolio`,
      description: parsed.basics.oneLineIntro || "Generated by GitHub Profile Studio.",
      imageAlt: `${titleName} GitHub profile preview`
    },
    favicon: {
      emoji: initials(titleName),
      background: "#ffffff",
      foreground: "#0969da"
    },
    staticAssets: [
      { path: "index.html", purpose: "GitHub Pages entry HTML" },
      { path: "style.css", purpose: "Responsive page styles" },
      { path: "script.js", purpose: "Theme and interaction script" },
      { path: "assets/profile-studio-config.json", purpose: "Serializable page configuration" },
      { path: "assets/og-image.png", purpose: "Open Graph social preview" },
      { path: "favicon.svg", purpose: "Generated favicon" }
    ]
  };
}

export function buildPageVisualExport(draft: NewUserFormDraft, overrides: Partial<PageVisualConfig> = {}) {
  const config = pageVisualConfigSchema.parse({ ...defaultPageVisualConfig(draft), ...overrides });
  return {
    config,
    seoTags: [
      `<title>${escapeHtml(config.seo.title ?? "GitHub Portfolio")}</title>`,
      `<meta name="description" content="${escapeHtml(config.seo.description ?? "")}">`,
      `<meta name="keywords" content="${escapeHtml(config.seo.keywords.join(", "))}">`,
      `<meta property="og:title" content="${escapeHtml(config.openGraph.title ?? config.seo.title ?? "GitHub Portfolio")}">`,
      `<meta property="og:description" content="${escapeHtml(config.openGraph.description ?? config.seo.description ?? "")}">`,
      `<meta property="og:image:alt" content="${escapeHtml(config.openGraph.imageAlt ?? "GitHub profile preview")}">`,
      '<link rel="icon" href="favicon.svg" type="image/svg+xml">'
    ],
    faviconSvg: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64"><rect width="64" height="64" rx="12" fill="${config.favicon.background}"/><text x="32" y="40" text-anchor="middle" font-size="22" font-family="Arial" fill="${config.favicon.foreground}">${escapeHtml(config.favicon.emoji)}</text></svg>`,
    staticAssets: config.staticAssets,
    acceptanceIds: [
      "N-PVIS-001",
      "N-PVIS-002",
      "N-PVIS-003",
      "N-PVIS-004",
      "N-PVIS-005",
      "N-PVIS-006",
      "N-PVIS-007",
      "N-PVIS-008",
      "N-PVIS-009",
      "N-PVIS-010",
      "N-PVIS-011",
      "N-POUT-007"
    ]
  };
}

function initials(value: string): string {
  return value
    .split(/\s+/)
    .map((part) => part[0])
    .filter(Boolean)
    .slice(0, 2)
    .join("")
    .toUpperCase() || "GH";
}

function escapeHtml(value: string): string {
  return value.replace(/[&<>"']/g, (char) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "\"": "&quot;", "'": "&#39;" }[char] ?? char));
}
